# Quiz 3

In [3]:
import numpy as np
import pennylane as qml

dev = qml.device("default.qubit", wires=3)


# YOUR CODE HERE: implement the circuit in the picture in the QNode below
# The QNode should return the measurement outcome probabilities on the 
# last two qubits.
@qml.qnode(dev)
def quiz_3_qnode(y):
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)
    qml.Hadamard(wires=2)
    qml.CZ(wires=[0,1])
    qml.CZ(wires=[1,2])
    
    outcome = qml.measure(wires=0)
    qml.cond(outcome, convert_to_y_basis)(y, wires=2)
        
    return qml.probs(wires=[1,2])

def convert_to_y_basis(y, wires):
    qml.Hadamard(wires=wires)
    qml.RY(y, wires=wires)
    



In [4]:
quiz_3_qnode(0)

QuantumFunctionError: Only a single qubit can be measured in the middle of the circuit

## 1.3

In [6]:
def part_a():
    """Write a quantum circuit that computes the Boolean function
        f(a, b, c, d) = ab + cd
    where the + here represents the XOR operation.

    The first four qubits of your circuit should correspond to the
    input variables, a, b, c, d, in that order. The last qubit of your
    circuit should correspond to the output. If you use an auxiliary wires
    in your circuit, these should be uncomputed, like so:
          _______
     a ---|  C  |--- a
     b ---|  I  |--- b
     c ---|  R  |--- c
     d ---|  C  |--- d
     0 ---|     |--- 0 # Optional aux. wires
     0 ---|     |--- 0
          ...
     0 ---=======--- ab + cd

    """

    # You can change this to as many wires as you need
    num_wires = 7

    # Do not change the number of shots on the device
    dev = qml.device("default.qubit", wires=num_wires, shots=1)

    @qml.qnode(dev)
    def my_circuit(a, b, c, d):
        """ Args:
                a, b, c, d (int): The input variables, either 0 or 1.

            Returns:
                array[int]: A single sample of the output of your circuit.
        """
        
        # YOUR CODE HERE
        # Apply some quantum gates
        # Don't forget to initialize the first 4 wires based on a, b, c, d
        if a:
            qml.PauliX(wires=0)
        if b:
            qml.PauliX(wires=1)
        if c:
            qml.PauliX(wires=2)
        if d:
            qml.PauliX(wires=3)
            
        qml.Toffoli(wires=[0,1,4])
        qml.Toffoli(wires=[2,3,6])
        qml.CNOT(wires=[4,6])
        qml.Toffoli(wires=[0,1,4])

        return qml.sample()

    return my_circuit


In [7]:
print(part_a()(1,1,1,0))

[1 1 1 0 0 0 1]


In [8]:
def part_b():
    """Write a quantum circuit that computes the Boolean function
        f(a, b, c) = NOT(a) * b * c
    where the * here represents the AND operation.

    The first three qubits of your circuit should correspond to the
    input variables, a, b, c, in that order. The last qubit of your
    circuit should correspond to the output. If you use an auxiliary wires
    in your circuit, these should be uncomputed.

          _______
     a ---|  C  |--- a
     b ---|  I  |--- b
     c ---|  R  |--- c
     0 ---|  C  |--- 0 # Optional aux. wires
     0 ---|     |--- 0
            ...
     0 ---=======--- NOT(a) * b * c

    """

    # You can change this to as many wires as you need
    num_wires = 6

    # Do not change the number of shots on the device
    dev = qml.device("default.qubit", wires=num_wires, shots=1)

    @qml.qnode(dev)
    def my_circuit(a, b, c):
        """ Args:
                a, b, c (int): The input variables, either 0 or 1.

            Returns:
                array[int]: A single sample of the output of your circuit.
        """
        
        # YOUR CODE HERE
        # Apply some quantum gates
        if a:
            qml.PauliX(wires=0)
        if b:
            qml.PauliX(wires=1)
        if c:
            qml.PauliX(wires=2)
            
        qml.PauliX(wires=3)
        qml.CNOT(wires=[0,3])
        qml.Toffoli(wires=[1,2,4])
        qml.Toffoli(wires=[3,4,5])
        qml.Toffoli(wires=[1,2,4])
        qml.CNOT(wires=[0,3])
        qml.PauliX(wires=3)
        
        return qml.sample(wires=[0,1,2,5])

    return my_circuit

In [9]:
print(part_b()(0,1,1))

[0 1 1 1]


In [10]:

def part_c():
    """Write a quantum circuit that computes the Boolean function
        f(a, b, c) = a + a * NOT(b) + NOT(a * b * c)
    where the * here represents the AND operation, and + the XOR.

    The first three qubits of your circuit should correspond to the
    input variables, a, b, c, in that order. The last qubit of your
    circuit should correspond to the output. If you use an auxiliary wires
    in your circuit, these should be uncomputed.
          _______
     a ---|  C  |--- a
     b ---|  I  |--- b
     c ---|  R  |--- c
     0 ---|  C  |--- 0 # Optional aux. wires
     0 ---|     | 0
            ...
     0 ---=======---- a + a * NOT(b) + NOT(a * b * c)

    """

    # You can change this to as many wires as you need
    num_wires = 6

    # Do not change the number of shots on the device
    dev = qml.device("default.qubit", wires=num_wires, shots=1)

    @qml.qnode(dev)
    def my_circuit(a, b, c):
        """ Args:
                a, b, c (int): The input variables, either 0 or 1.

            Returns:
                array[int]: A single sample of the output of your circuit.
        """
        
        # YOUR CODE HERE
        # Apply some quantum gates
        if a:
            qml.PauliX(wires=0)
        if b:
            qml.PauliX(wires=1)
        if c:
            qml.PauliX(wires=2)
            
        qml.PauliX(wires=1)
        qml.Toffoli(wires=[0,1,3])
        qml.PauliX(wires=1)
        qml.CNOT(wires=[0,3]) # a + a*NOT(b)
        
        qml.Toffoli(wires=[0,1,5])
        qml.Toffoli(wires=[2,5,4])
        qml.Toffoli(wires=[0,1,5])
        qml.PauliX(wires=4) # NOT(a*b*c)
        
        qml.CNOT(wires=[3,4])
        qml.CNOT(wires=[0,3])
        
        return qml.sample(wires=[0,1,2,3,4])

    return my_circuit

In [16]:
#f(a, b, c) = a + a * NOT(b) + NOT(a * b * c)
a,b,c = 1,1,0
print(part_c()(a,b,c))
x = a and not b
y = not (a and b and c)
xor = (a and not x) or (not a and x)
xor = xor != y
print(x,y,xor)

[1 1 0 0 0]
False True False


In [144]:
def part_d():
    """Write a quantum circuit that computes the function
        f(a, b) = a + b
    where a, b are two-bit binary values, and + is regular binary addition.

    The first four qubits of your circuit should correspond to the input
    variables, a[0], a[1], b[0], b[1], in that order. The last three qubits of your
    circuit should correspond to the output in the order: carry, (a + b)[0], (a + b)[1].
    If you use an auxiliary wires in your circuit, these should be uncomputed.
           _______
     a0 ---|  C  |--- a0
     a1 ---|  I  |--- a1
     b0 ---|  R  |--- b0
     b1 ---|  C  |--- b1
      0 ---|     |--- 0 # Optional aux wires
             ...
      0 ---|     |--- 0
      0 ---|     |--- carry
      0 ---|     |--- s0
      0 ---=======--- s1

    """

    # You can change this to as many wires as you need
    num_wires = 10

    # Do not change the number of shots on the device
    dev = qml.device("default.qubit", wires=num_wires, shots=1)

    @qml.qnode(dev)
    def my_circuit(a, b):
        """ Args:
                a, b (list([int])): The input variables. For example, a = [1, 0] corresponds
                to a decimal value of 2.

            Returns:
                array[int]: A single sample of the output of your circuit.
        """
        
        # YOUR CODE HERE
        # Apply some quantum gates
        if a[0]:
            qml.PauliX(wires=0)
        if a[1]:
            qml.PauliX(wires=1)
        if b[0]:
            qml.PauliX(wires=2)
        if b[1]:
            qml.PauliX(wires=3)

        qml.CNOT(wires=[1,9]) # copy a1 to s1
        qml.CNOT(wires=[3,9]) # setting s1

        qml.CNOT(wires=[0,8]) # copy a0 to s0
        qml.CNOT(wires=[2,8]) # XOR of a0 b0
        qml.Toffoli(wires=[1,3,4]) # carry of 0th bit
        qml.Toffoli(wires=[4,8,5]) # AND carry of 0th bit and XOR of a0 b0
        qml.Toffoli(wires=[0,2,6]) # carry of 1st bit

        # OR 4 and 5
        qml.PauliX(wires=5)
        qml.PauliX(wires=6)
        qml.PauliX(wires=7)
        qml.Toffoli(wires=[5,6,7]) # setting carry
        qml.PauliX(wires=5)
        qml.PauliX(wires=6)
        
        qml.Toffoli(wires=[4,9,5]) # reset 5
        qml.CNOT(wires=[4,8]) # setting s1
        qml.Toffoli(wires=[1,3,6]) # reset 6
        qml.Toffoli(wires=[0,2,4]) # reset 4

        return qml.sample()

    return my_circuit

In [145]:
# a = [0,0]
# b = [0,0]
# for i in range(16):
#     a[0] = i % 2
#     a[1] = (i >> 1) % 2
#     b[0] = (i >> 2) % 2
#     b[1] = (i >> 3) % 2
#     for j in range(4,7):
#         assert part_d()(a,b)[j] == 0

#     print(0, a[1],a[0])
#     print(0, b[1],b[0])
#     print(part_d()(a,b)[7],part_d()(a,b)[9],part_d()(a,b)[8])
#     print('\n')

a = [1,1]
b = [1,1]
print(0, a[:])
print(0, b[:])
print(part_d()(a,b)[7:10])
print(part_d()(a,b)[4:7])
print(part_d()(a,b))

0 [1, 1]
0 [1, 1]
[1 1 0]
[0 0 0]
[1 1 1 1 0 0 0 1 1 0]
